- name: Add test toolchain repo
  apt_repository:
    repo: "ppa:ubuntu-toolchain-r/test"
    state: present
- name: add into apt key
  shell: "curl -L https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | apt-key add -"
- name: add intel repo
  apt_repository:
    repo: "deb https://apt.repos.intel.com/oneapi all main"
- name: Install core libs
  apt:
    update_cache: true
    name:
    - awscli
    - build-essential
    - ca-certificates
    - ccache
    - cifs-utils
    - clang
    - clangd
    - clang-format
    - clang-tools
    - cmake
    - curl
    - debhelper
    - doxygen
    - dpkg-sig
    - fd-find
    - ffmpeg
    - flac
    - fzf
    - g++-9
    - gcc-9
    - git
    - git-lfs
    - gnupg2
    - intel-oneapi-mkl-2021.1.1
    - intel-oneapi-mkl-devel-2021.1.1
    - libboost-all-dev
    - libbz2-dev
    - libffi-dev
    - libflac++-dev
    - libflac-dev
    - libfontconfig1-dev
    - libfreetype6-dev
    - libgdbm-dev
    - libicu-dev
    - liblzma-dev
    - libncursesw5-dev
    - libpthread-stubs0-dev
    - libreadline-dev
    - libsndfile1
    - libsndfile1-dev
    - libsox-dev
    - libsox-fmt-all
    - libsqlite3-dev
    - libssl-dev
    - libtcmalloc-minimal4
    - libxcb-xfixes0-dev
    - libxkbcommon-dev
    - llvm
    - locales
    - lsb-core
    - lzma-dev
    - manpages-dev
    - nasm
    - neovim
    - openjdk-11-jdk
    - pandoc
    - patchelf
    - pkg-config
    - python3
    - python3.10-venv
    - python3-boto3
    - ripgrep
    - shunit2
    - sndfile-programs
    - sox
    - stow
    - suckless-tools
    - tk-dev
    - tmux
    - unzip
    - wget
    - yasm
    - zlib1g-dev
    - apt-transport-https
    - software-properties-common
    - curl
