- name: Remove old versions of docker
  apt:
    name: ['apt-get', 'remove',  'docker', 'docker-engine', 'docker.io containerd', 'runc']
    state: absent
- name: Get key utils
  apt:
    name: ['ca-certificates', 'curl', 'gnupg', 'lsb-release']
    state: present
- name: Make keyrings dir
  file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: '0755'
- name: Get docker key
  shell: 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg'
- name: Install docker key
  shell: 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null'
- name: Install Docker
  apt:
    update_cache: true
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose-plugin']
    state: present
- name: Add self to docker group
  shell: "usermod -a -G docker {{ local_user }}"
